//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Employees
    {
        public Employees()
        {
            this.Employees1 = new HashSet<Employees>();
            this.Orders = new HashSet<Orders>();
            this.Territories = new HashSet<Territories>();
        }

        [DisplayName("員工編號")]
        public int EmployeeID { get; set; }

        [DisplayName("姓名")]
        public string LastName { get; set; }

        [DisplayName("姓氏")]
        public string FirstName { get; set; }

        [DisplayName("職稱")]
        public string Title { get; set; }

        [DisplayName("稱謂")]
        public string TitleOfCourtesy { get; set; }

        [DisplayName("生日")]
        public Nullable<System.DateTime> BirthDate { get; set; }

        [DisplayName("應聘日期")]
        public Nullable<System.DateTime> HireDate { get; set; }

        [DisplayName("地址")]
        public string Address { get; set; }

        [DisplayName("城市")]
        public string City { get; set; }

        [DisplayName("地區")]
        public string Region { get; set; }

        [DisplayName("郵遞區號")]
        public string PostalCode { get; set; }

        [DisplayName("國家")]
        public string Country { get; set; }

        [DisplayName("家用電話")]
        public string HomePhone { get; set; }

        [DisplayName("分機")]
        public string Extension { get; set; }

        [DisplayName("照片")]
        public byte[] Photo { get; set; }

        [DisplayName("筆記")]
        public string Notes { get; set; }

        [DisplayName("上級")]
        public Nullable<int> ReportsTo { get; set; }

        [DisplayName("照片路徑")]
        public string PhotoPath { get; set; }
    
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Territories> Territories { get; set; }
    }
}
