//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order_Details
    {
        [DisplayName("訂單編號")]
        public int OrderID { get; set; }

        [DisplayName("產品編號")]
        public int ProductID { get; set; }

        [DisplayName("單價")]
        public decimal UnitPrice { get; set; }

        [DisplayName("數量")]
        public short Quantity { get; set; }

        [DisplayName("折扣")]
        public float Discount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
