//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Orders
    {
        public Orders()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }

        [DisplayName("訂單編號")]
        public int OrderID { get; set; }

        [DisplayName("客戶編號")]
        public string CustomerID { get; set; }

        [DisplayName("員工編號")]
        public Nullable<int> EmployeeID { get; set; }

        [DisplayName("下訂日期")]
        public Nullable<System.DateTime> OrderDate { get; set; }

        [DisplayName("需求日期")]
        public Nullable<System.DateTime> RequiredDate { get; set; }

        [DisplayName("出貨日期")]
        public Nullable<System.DateTime> ShippedDate { get; set; }

        [DisplayName("運貨商")]
        public Nullable<int> ShipVia { get; set; }

        [DisplayName("運費")]
        public Nullable<decimal> Freight { get; set; }

        [DisplayName("收貨人名稱")]
        public string ShipName { get; set; }

        [DisplayName("收貨地址")]
        public string ShipAddress { get; set; }

        [DisplayName("收貨城市")]
        public string ShipCity { get; set; }

        [DisplayName("收貨地區")]
        public string ShipRegion { get; set; }

        [DisplayName("收貨郵遞區號")]
        public string ShipPostalCode { get; set; }

        [DisplayName("收貨國家")]
        public string ShipCountry { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Shippers Shippers { get; set; }
    }
}
