//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Products
    {
        public Products()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }

        [DisplayName("產品編號")]
        public int ProductID { get; set; }

        [DisplayName("產品名稱")]
        public string ProductName { get; set; }

        [DisplayName("廠商編號")]
        public Nullable<int> SupplierID { get; set; }

        [DisplayName("類別編號")]
        public Nullable<int> CategoryID { get; set; }

        [DisplayName("每單位數量")]
        public string QuantityPerUnit { get; set; }

        [DisplayName("單價")]
        public Nullable<decimal> UnitPrice { get; set; }

        [DisplayName("庫存單位")]
        public Nullable<short> UnitsInStock { get; set; }

        [DisplayName("訂購單位")]
        public Nullable<short> UnitsOnOrder { get; set; }

        [DisplayName("再次訂購量")]
        public Nullable<short> ReorderLevel { get; set; }

        [DisplayName("是否停產")]
        public bool Discontinued { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
