//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Region
    {
        public Region()
        {
            this.Territories = new HashSet<Territories>();
        }

        [DisplayName("地區編號")]
        public int RegionID { get; set; }

        [DisplayName("地區描述")]
        public string RegionDescription { get; set; }
    
        public virtual ICollection<Territories> Territories { get; set; }
    }
}
