//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Suppliers
    {
        public Suppliers()
        {
            this.Products = new HashSet<Products>();
        }

        [DisplayName("供應商編號")]
        public int SupplierID { get; set; }

        [DisplayName("公司名稱")]
        public string CompanyName { get; set; }

        [DisplayName("聯絡人")]
        public string ContactName { get; set; }

        [DisplayName("稱謂")]
        public string ContactTitle { get; set; }

        [DisplayName("地址")]
        public string Address { get; set; }

        [DisplayName("城市")]
        public string City { get; set; }

        [DisplayName("地區")]
        public string Region { get; set; }

        [DisplayName("郵遞區號")]
        public string PostalCode { get; set; }

        [DisplayName("國家")]
        public string Country { get; set; }

        [DisplayName("電話")]
        public string Phone { get; set; }

        [DisplayName("傳真")]
        public string Fax { get; set; }

        [DisplayName("首頁")]
        public string HomePage { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
